---
title: "tidy tuesday 2022-06-07"
author: "Scout Leonard"
date: "6/07/2022"
output: html_document
---

# Load Libraries

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
librarian::shelf(tidyverse,
                 here,
                 tidytuesdayR,
                 janitor)
```

# Read in Data

```{r}
tuesdata <- tidytuesdayR::tt_load('2022-06-07')

pride_aggregates <- tuesdata$pride_aggregates %>% 
  clean_names()

pride_sponsors <- tuesdata$pride_sponsors %>% 
  clean_names()
```

# Join Politicans and Pride Data

```{r}
events_politicians_joined <- left_join(pride_sponsors, pride_aggregates) %>% 
  group_by(company) %>% 
  summarise(politicians_total = sum(number_of_politicians_contributed_to)) %>% 
  na.omit() %>% 
  
```

# Visualize

```{r}
ggplot(data = events_politicians_joined, aes(x = company, y = politicians_total)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  facet_wrap(~pride_event_sponsored) +
  theme_minimal()
```

