---
title: "Appa"
author: "Scout Leonard"
date: "12/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(stringr)
library(ggimage)
library(here)

iroh = here("2020-08-11","images", "iroh_2.png")
```

```{r}
tuesdata <- tidytuesdayR::tt_load('2020-08-11')

avatar <- tuesdata$avatar
```

```{r}
tea_data <- avatar %>% 
  mutate(tea_mentions = str_count(full_text,
                                 " tea ")) %>% 
  group_by(character) %>% 
  summarise(tea_mentions_sum = sum(tea_mentions, na.rm = TRUE)) %>% 
  filter(tea_mentions_sum > 0) %>% 
  filter(character != "Scene Description")

team_mentions_max = max(tea_data$tea_mentions_sum)
```

```{r}
tea_data$index <- 1:nrow(tea_data)

number_characters = nrow(tea_data)
id = seq(1:number_characters)
angle = 90 - 360 * (id) / number_characters
tea_data$angle = ifelse(angle < -90, angle + 180, angle)

ggplot(data = tea_data) +
  geom_segment(aes(x = index,
                   xend = index,
                   y = 0,
                   yend = tea_mentions_sum),
               color = "cornsilk") +
  geom_segment(aes(x = index,
                   xend = index,
                   y = tea_mentions_sum,
                   yend = team_mentions_max),
               linetype = 'dotted',
               color = "cornsilk") +
  geom_image(aes(x = 8.5,
                 y = -15,
                 image = iroh),
             size = .25) +
  geom_segment(x = 0,
               xend = 17,
               y = 0,
               yend = 0,
               color = "cornsilk") +
   coord_polar() +
   xlim(0, 17) +
   ylim(-15, 35) +
  geom_text(aes(x = index,
                y = 30,
                label = paste0(character, " : ", tea_mentions_sum)),
            angle = angle,
            family = 'serif',
            color = "cornsilk") +
  labs(title = "Avatar the Last Airbender: \n Who drinks the most tea?",
       subtitle = "How many times does each character say the word 'tea'\n throughout the series?") +
  theme(panel.background = element_rect("#3D2D19"),
        plot.background = element_rect(fill = "#3D2D19"),
        panel.grid = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        text = element_text(family = 'serif',
                            color = "cornsilk"),
        plot.title = element_text(size = 16, face = 'bold'),
        plot.subtitle = element_text(size = 10))

```



