---
title: "Tidy Tuesday 2021-09-14"
author: "Scout Leonard"
date: "9/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(lubridate)
library(tidytuesdayR)
library(tidyverse)
library(skimr)
library(paletteer)
```

```{r}
#read in the data
tuesdata <- tidytuesdayR::tt_load('2021-09-14')
```
```{r}
# look at the first dataset, billboard

billboard <- tuesdata$billboard

summary(billboard)

skim(billboard)

dim(billboard)

names(billboard)
```

```{r}
# look at the second dataset, audio_features

audio_features <- tuesdata$audio_features

summary(audio_features)

skim(audio_features)

dim(audio_features)

names(audio_features)
```
```{r}
#create a taylor swift subset

tswift_data <- audio_features %>% 
  filter(performer == "Taylor Swift") %>% 
  filter(spotify_track_album == "Taylor Swift" | spotify_track_album == "Fearless" | spotify_track_album == "Speak Now" | spotify_track_album == "Red" | spotify_track_album == "1989" | spotify_track_album == "reputation" | spotify_track_album == "Lover" | spotify_track_album == "{'album_type': 'album', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02'}, 'href': 'https://api.spotify.com/v1/artists/06HL4z0CvFAxyc27GXpf02', 'id': '06HL4z0CvFAxyc27GXpf02', 'name': 'Taylor Swift', 'type': 'artist', 'uri': 'spotify:artist:06HL4z0CvFAxyc27GXpf02'}], 'available_markets': ['AD', 'AE', 'AG', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BN', 'BO', 'BR', 'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CH', 'CI', 'CL', 'CM', 'CO', 'CR', 'CV', 'CW', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ES', 'FI', 'FJ', 'FM', 'FR', 'GA', 'GB', 'GD', 'GE', 'GH', 'GM', 'GN', 'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KR', 'KW', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'MA', 'MC', 'MD', 'ME', 'MG', 'MH', 'MK', 'ML', 'MN', 'MO', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NZ', 'OM', 'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT', 'PW', 'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SE', 'SG', 'SI', 'SK', 'SL', 'SM', 'SN', 'SR', 'ST', 'SV', 'SZ', 'TD', 'TG', 'TH', 'TL', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VC', 'VN', 'VU', 'WS', 'XK', 'ZA', 'ZM', 'ZW'], 'external_urls': {'spotify': 'https://open.spotify.com/album/2fenSS68JI1h4Fo296JfGr'}, 'href': 'https://api.spotify.com/v1/albums/2fenSS68JI1h4Fo296JfGr', 'id': '2fenSS68JI1h4Fo296JfGr', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b27395f754318336a07e85ec59bc', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e0295f754318336a07e85ec59bc', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d0000485195f754318336a07e85ec59bc', 'width': 64}], 'name': 'folklore', 'release_date': '2020-07-24', 'release_date_precision': 'day', 'total_tracks': 16, 'type': 'album', 'uri': 'spotify:album:2fenSS68JI1h4Fo296JfGr'}
" | spotify_track_album == "{'album_type': 'album', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02'}, 'href': 'https://api.spotify.com/v1/artists/06HL4z0CvFAxyc27GXpf02', 'id': '06HL4z0CvFAxyc27GXpf02', 'name': 'Taylor Swift', 'type': 'artist', 'uri': 'spotify:artist:06HL4z0CvFAxyc27GXpf02'}], 'available_markets': ['AD', 'AE', 'AG', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BN', 'BO', 'BR', 'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CH', 'CI', 'CL', 'CM', 'CO', 'CR', 'CV', 'CW', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ES', 'FI', 'FJ', 'FM', 'FR', 'GA', 'GB', 'GD', 'GE', 'GH', 'GM', 'GN', 'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IS', 'IT', 'JM', 'JO', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KR', 'KW', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'MA', 'MC', 'MD', 'ME', 'MG', 'MH', 'MK', 'ML', 'MN', 'MO', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NZ', 'OM', 'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT', 'PW', 'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SE', 'SG', 'SI', 'SK', 'SL', 'SM', 'SN', 'SR', 'ST', 'SV', 'SZ', 'TD', 'TG', 'TH', 'TL', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VC', 'VN', 'VU', 'WS', 'XK', 'ZA', 'ZM', 'ZW'], 'external_urls': {'spotify': 'https://open.spotify.com/album/2Xoteh7uEpea4TohMxjtaq'}, 'href': 'https://api.spotify.com/v1/albums/2Xoteh7uEpea4TohMxjtaq', 'id': '2Xoteh7uEpea4TohMxjtaq', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b27333b8541201f1ef38941024be', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e0233b8541201f1ef38941024be', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d0000485133b8541201f1ef38941024be', 'width': 64}], 'name': 'evermore', 'release_date': '2020-12-11', 'release_date_precision': 'day', 'total_tracks': 15, 'type': 'album', 'uri': 'spotify:album:2Xoteh7uEpea4TohMxjtaq'}
") 

tswift_data_calculations <- tswift_data %>% 
  

ggplot(data = tswift_data, aes(x = song, y = danceability)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  facet_wrap(~ spotify_track_album, ncol = 1) +
  labs(title = "Taylor Swift")
```

